import { createContext, useContext, useState } from 'react';

const LangContext = createContext(null);

// ─── Từ điển ────────────────────────────────────────────────────────────────
export const TRANSLATIONS = {
  // ── Navigation / Sidebar ──────────────────────────────────────────────────
  'nav.explore':        { vi: 'Khám phá',     en: 'Explore' },
  'nav.library':        { vi: 'Thư viện',     en: 'Library' },
  'nav.account':        { vi: 'Tài khoản',    en: 'Account' },
  'nav.home':           { vi: 'Trang chủ',    en: 'Home' },
'nav.templates':      { vi: 'Templates',    en: 'Templates' },
'nav.sale':           { vi: 'Săn Sale',     en: 'Flash Sale' },
  'nav.downloads':      { vi: 'Downloads',    en: 'Downloads' },
  'nav.wishlist':       { vi: 'Yêu thích',    en: 'Wishlist' },
  'nav.notifications':  { vi: 'Thông báo',    en: 'Notifications' },
  'nav.coupons':        { vi: 'Mã giảm giá',  en: 'Coupons' },
  'nav.profile':        { vi: 'Hồ sơ',        en: 'Profile' },
  'nav.purchases':      { vi: 'Đơn mua',      en: 'Purchases' },
  'nav.reviews':        { vi: 'Reviews',       en: 'Reviews' },
  'nav.support':        { vi: 'Hỗ trợ',       en: 'Support' },
  'nav.affiliate':      { vi: 'Affiliate',     en: 'Affiliate' },
  'nav.login':          { vi: 'Đăng nhập',    en: 'Login' },
  'nav.register':       { vi: 'Đăng ký',      en: 'Register' },
  'nav.logout':         { vi: 'Đăng xuất',    en: 'Logout' },
  'nav.user_default':   { vi: 'Người dùng',   en: 'User' },
  'nav.security':       { vi: 'Bảo mật',      en: 'Security' },
  'nav.news':           { vi: 'Bảng tin',     en: 'News' },
  'nav.community': { vi: 'Cộng đồng', en: 'Community' },
  // ── Bottom Nav ────────────────────────────────────────────────────────────
  'bottom.explore':     { vi: 'Khám phá',  en: 'Explore' },
  'bottom.profile':     { vi: 'Hồ sơ',     en: 'Profile' },
  'bottom.downloads':   { vi: 'Downloads', en: 'Downloads' },
  'bottom.wishlist':    { vi: 'Yêu thích', en: 'Wishlist' },
  'bottom.notif':       { vi: 'Tin',       en: 'Alerts' },
  'bottom.login':       { vi: 'Đăng nhập',en: 'Login' },
  'bottom.register':    { vi: 'Đăng ký',  en: 'Register' },
  'bottom.logout':      { vi: 'Thoát',    en: 'Logout' },
  'bottom.light':       { vi: 'Sáng',     en: 'Light' },
  'bottom.dark':        { vi: 'Tối',      en: 'Dark' },

  // ── Theme Toggle ──────────────────────────────────────────────────────────
  'theme.dark':         { vi: 'Tối',      en: 'Dark' },
  'theme.light':        { vi: 'Sáng',     en: 'Light' },
  'theme.to_light':     { vi: 'Chuyển sang sáng', en: 'Switch to light' },
  'theme.to_dark':      { vi: 'Chuyển sang tối',  en: 'Switch to dark' },

  // ── Common ────────────────────────────────────────────────────────────────
  'common.loading':     { vi: 'Đang tải…',    en: 'Loading…' },
  'common.error':       { vi: 'Lỗi',           en: 'Error' },
  'common.save':        { vi: 'Lưu',           en: 'Save' },
  'common.cancel':      { vi: 'Hủy',           en: 'Cancel' },
  'common.confirm':     { vi: 'Xác nhận',      en: 'Confirm' },
  'common.close':       { vi: 'Đóng',          en: 'Close' },
  'common.search':      { vi: 'Tìm kiếm…',     en: 'Search…' },
  'common.filter':      { vi: 'Lọc',           en: 'Filter' },
  'common.all':         { vi: 'Tất cả',        en: 'All' },
  'common.free':        { vi: 'Miễn phí',      en: 'Free' },
  'common.paid':        { vi: 'Trả phí',       en: 'Paid' },
  'common.back':        { vi: 'Về trang chủ',  en: 'Back to home' },
  'common.submit':      { vi: 'Gửi',           en: 'Submit' },
  'common.edit':        { vi: 'Chỉnh sửa',     en: 'Edit' },
  'common.delete':      { vi: 'Xóa',           en: 'Delete' },
  'common.view':        { vi: 'Xem',           en: 'View' },
  'common.download':    { vi: 'Tải xuống',     en: 'Download' },
  'common.preview':     { vi: 'Xem trước',     en: 'Preview' },
  'common.copy':        { vi: 'Sao chép',      en: 'Copy' },
  'common.copied':      { vi: 'Đã sao chép!',  en: 'Copied!' },
  'common.share':       { vi: 'Chia sẻ',       en: 'Share' },
  'common.buy':         { vi: 'Mua ngay',      en: 'Buy now' },
  'common.add_wish':    { vi: 'Thêm yêu thích',en: 'Add to wishlist' },
  'common.remove_wish': { vi: 'Bỏ yêu thích',  en: 'Remove from wishlist' },
  'common.no_results':  { vi: 'Không có kết quả', en: 'No results' },
  'common.retry':       { vi: 'Thử lại',       en: 'Retry' },

  // ── Auth pages ─────────────────────────────────────────────────────────────
  'auth.login_title':    { vi: 'Đăng nhập',        en: 'Login' },
  'auth.register_title': { vi: 'Tạo tài khoản',    en: 'Create account' },
  'auth.email':          { vi: 'Email',              en: 'Email' },
  'auth.password':       { vi: 'Mật khẩu',          en: 'Password' },
  'auth.full_name':      { vi: 'Họ và tên',          en: 'Full name' },
  'auth.forgot_pw':      { vi: 'Quên mật khẩu?',    en: 'Forgot password?' },
  'auth.no_account':     { vi: 'Chưa có tài khoản?',en: 'No account yet?' },
  'auth.has_account':    { vi: 'Đã có tài khoản?',  en: 'Already have an account?' },
  'auth.login_btn':      { vi: 'Đăng nhập',         en: 'Sign in' },
  'auth.register_btn':   { vi: 'Tạo tài khoản',     en: 'Create account' },
  'auth.resend_verify':  { vi: 'Gửi lại email xác minh', en: 'Resend verification email' },
  'auth.show_pw':        { vi: 'Hiện',   en: 'Show' },
  'auth.hide_pw':        { vi: 'Ẩn',    en: 'Hide' },

  // ── Templates page ─────────────────────────────────────────────────────────
  'tpl.title':          { vi: 'Templates',           en: 'Templates' },
  'tpl.sort_newest':    { vi: 'Mới nhất',            en: 'Newest' },
  'tpl.sort_popular':   { vi: 'Phổ biến',            en: 'Popular' },
  'tpl.sort_price_asc': { vi: 'Giá tăng dần',        en: 'Price: Low to High' },
  'tpl.sort_price_desc':{ vi: 'Giá giảm dần',        en: 'Price: High to Low' },
  'tpl.sort_rating':    { vi: 'Đánh giá cao',        en: 'Top Rated' },
  'tpl.sort_discount':  { vi: '💸 Giảm nhiều nhất', en: '💸 Highest Discount' },
  'tpl.category':       { vi: 'Danh mục',            en: 'Category' },
  'tpl.tag':            { vi: 'Tag',                  en: 'Tag' },
  'tpl.empty':          { vi: 'Không có template nào', en: 'No templates found' },
  'tpl.sales':          { vi: 'lượt mua',            en: 'sales' },
  'tpl.downloads':      { vi: 'lượt tải',            en: 'downloads' },

  // ── Profile page ───────────────────────────────────────────────────────────
  'profile.title':      { vi: 'Hồ sơ cá nhân',      en: 'Profile' },
  'profile.save':       { vi: 'Lưu thay đổi',        en: 'Save changes' },
  'profile.avatar':     { vi: 'Ảnh đại diện',        en: 'Avatar' },
  'profile.name':       { vi: 'Họ và tên',           en: 'Full name' },
  'profile.bio':        { vi: 'Giới thiệu',          en: 'Bio' },
  'profile.website':    { vi: 'Website',              en: 'Website' },
  'profile.updated':    { vi: 'Đã cập nhật hồ sơ!', en: 'Profile updated!' },

  // ── Purchases ──────────────────────────────────────────────────────────────
  'purchase.title':     { vi: 'Đơn mua',             en: 'Purchases' },
  'purchase.empty':     { vi: 'Chưa có đơn mua nào', en: 'No purchases yet' },
  'purchase.status_pending':   { vi: 'Chờ thanh toán', en: 'Pending' },
  'purchase.status_paid':      { vi: 'Đã thanh toán',  en: 'Paid' },
  'purchase.status_cancelled': { vi: 'Đã hủy',         en: 'Cancelled' },
  'purchase.status_refunded':  { vi: 'Đã hoàn tiền',   en: 'Refunded' },

  // ── Downloads ──────────────────────────────────────────────────────────────
  'dl.title':           { vi: 'Downloads',            en: 'Downloads' },
  'dl.empty':           { vi: 'Chưa có file nào',     en: 'No downloads yet' },

  // ── Wishlist ───────────────────────────────────────────────────────────────
  'wish.title':         { vi: 'Yêu thích',            en: 'Wishlist' },
  'wish.empty':         { vi: 'Chưa có template yêu thích', en: 'No wishlist items yet' },

  // ── Notifications ──────────────────────────────────────────────────────────
  'notif.title':        { vi: 'Thông báo',            en: 'Notifications' },
  'notif.empty':        { vi: 'Không có thông báo',   en: 'No notifications' },
  'notif.mark_all':     { vi: 'Đánh dấu tất cả đã đọc', en: 'Mark all as read' },

  // ── Reviews ────────────────────────────────────────────────────────────────
  'review.title':       { vi: 'Đánh giá của tôi',    en: 'My Reviews' },
  'review.empty':       { vi: 'Chưa có đánh giá nào', en: 'No reviews yet' },

  // ── Tickets ────────────────────────────────────────────────────────────────
  'ticket.title':       { vi: 'Hỗ trợ',              en: 'Support Tickets' },
  'ticket.new':         { vi: 'Tạo ticket',           en: 'New ticket' },
  'ticket.empty':       { vi: 'Chưa có ticket nào',  en: 'No tickets yet' },
  'ticket.status_open':   { vi: 'Đang mở',   en: 'Open' },
  'ticket.status_closed': { vi: 'Đã đóng',   en: 'Closed' },

  // ── Affiliate ─────────────────────────────────────────────────────────────
  'aff.title':          { vi: 'Affiliate',            en: 'Affiliate' },
  'aff.link':           { vi: 'Link giới thiệu',      en: 'Referral link' },
  'aff.commission':     { vi: 'Hoa hồng',             en: 'Commission' },
  'aff.balance':        { vi: 'Số dư',                en: 'Balance' },
  'aff.withdraw':       { vi: 'Rút tiền',             en: 'Withdraw' },

  // ── Coupons ────────────────────────────────────────────────────────────────
  'coupon.title':       { vi: 'Mã giảm giá',          en: 'Coupons' },
  'coupon.empty':       { vi: 'Không có mã giảm giá', en: 'No coupons available' },

  // ── Security ──────────────────────────────────────────────────────────────
  'security.title':     { vi: 'Bảo mật',              en: 'Security' },
  'security.change_pw': { vi: 'Đổi mật khẩu',         en: 'Change password' },
  'security.current_pw':{ vi: 'Mật khẩu hiện tại',    en: 'Current password' },
  'security.new_pw':    { vi: 'Mật khẩu mới',         en: 'New password' },
  'security.confirm_pw':{ vi: 'Xác nhận mật khẩu',    en: 'Confirm password' },

  // ── 404 ───────────────────────────────────────────────────────────────────
  '404.text':           { vi: 'Không tìm thấy',       en: 'Not found' },
  '404.back':           { vi: '← Về trang chủ',       en: '← Back to home' },
  // ── Layout / UI chung ─────────────────────────────────────────────────────
'layout.open_menu':         { vi: 'Mở menu',                      en: 'Open menu' },
'ui.loading':               { vi: 'Đang tải...',                  en: 'Loading...' },
'ui.click_to_notify':       { vi: 'Nhấn để xem thông báo →',     en: 'Click to view notifications →' },
'ui.prev':                  { vi: '← Trước',                      en: '← Prev' },
'ui.next':                  { vi: 'Tiếp →',                       en: 'Next →' },
'ui.no_data':               { vi: 'Không có dữ liệu',             en: 'No data' },

// ── Status Badge ──────────────────────────────────────────────────────────
'status.paid':              { vi: 'Đã thanh toán',                en: 'Paid' },
'status.pending':           { vi: 'Chờ xử lý',                   en: 'Pending' },
'status.cancelled':         { vi: 'Đã hủy',                      en: 'Cancelled' },
'status.completed':         { vi: 'Hoàn thành',                   en: 'Completed' },
'status.open':              { vi: 'Mở',                           en: 'Open' },
'status.in_progress':       { vi: 'Đang xử lý',                  en: 'In Progress' },
'status.resolved':          { vi: 'Đã giải quyết',               en: 'Resolved' },
'status.closed':            { vi: 'Đã đóng',                     en: 'Closed' },
'status.failed':            { vi: 'Thất bại',                    en: 'Failed' },

// ── MobileSidebar ─────────────────────────────────────────────────────────
'sidebar.account_section':  { vi: 'Tài khoản',                   en: 'Account' },
'sidebar.login':            { vi: '🔐 Đăng nhập',                en: '🔐 Login' },
'sidebar.register_free':    { vi: '✨ Đăng ký miễn phí',         en: '✨ Register free' },
'sidebar.logout':           { vi: 'Đăng xuất',                   en: 'Logout' },

// ── ThemeToggle / LangToggle ──────────────────────────────────────────────
'lang.vi':                  { vi: 'Tiếng Việt',                  en: 'Vietnamese' },
'lang.en':                  { vi: 'Tiếng Anh',                   en: 'English' },
'lang.switch_to_vi':        { vi: 'Chuyển sang Tiếng Việt',      en: 'Switch to Vietnamese' },
'lang.switch_to_en':        { vi: 'Chuyển sang Tiếng Anh',       en: 'Switch to English' },

// ── Notifications Page ────────────────────────────────────────────────────
'notif.total':              { vi: 'thông báo',                   en: 'notifications' },
'notif.unread':             { vi: 'chưa đọc',                    en: 'unread' },
'notif.unread_only':        { vi: 'Chưa đọc',                    en: 'Unread' },
'notif.mark_one_read':      { vi: 'Đánh dấu đã đọc',            en: 'Mark as read' },
'notif.view_detail':        { vi: 'Xem chi tiết →',              en: 'View detail →' },
'notif.unread_count': { vi: 'chưa đọc', en: 'unread' },
'notif.read_all_btn':       { vi: '✓ Đọc tất cả',               en: '✓ Read all' },
'notif.empty_unread':       { vi: 'Bạn đã đọc hết thông báo rồi.', en: 'You have read all notifications.' },
'notif.empty_all':          { vi: 'Thông báo sẽ xuất hiện ở đây.', en: 'Notifications will appear here.' },
'notif.empty_title':        { vi: 'Không có thông báo nào',         en: 'No notifications' },

// ── Register Page ─────────────────────────────────────────────────────────
'register.tagline':         { vi: 'Tham gia Qtemplate — miễn phí mãi mãi ✨', en: 'Join Qtemplate — free forever ✨' },
'register.full_name_lbl':   { vi: 'Họ và tên',                   en: 'Full name' },
'register.pw_label':        { vi: 'Mật khẩu',                    en: 'Password' },
'register.pw_confirm_lbl':  { vi: 'Xác nhận mật khẩu',           en: 'Confirm password' },
'register.pw_confirm_ph':   { vi: 'Nhập lại mật khẩu',           en: 'Re-enter password' },
'register.pw_match':        { vi: '✓ Mật khẩu khớp',            en: '✓ Passwords match' },
'register.pw_no_match':     { vi: '✗ Không khớp',               en: '✗ Do not match' },
'register.creating':        { vi: 'Đang tạo tài khoản...',       en: 'Creating account...' },
'register.create_btn':      { vi: 'Tạo tài khoản',               en: 'Create account' },
'register.has_account':     { vi: 'Đã có tài khoản?',            en: 'Already have an account?' },
'register.terms':           { vi: 'Bằng cách đăng ký, bạn đồng ý với', en: 'By registering, you agree to our' },
'register.terms_link':      { vi: 'Điều khoản dịch vụ',          en: 'Terms of Service' },
'register.name_ph':         { vi: 'Nguyễn Văn A',                en: 'John Doe' },
'register.success':         { vi: 'Đăng ký thành công! Đang chuyển hướng...', en: 'Registered successfully! Redirecting...' },
'register.err_name':        { vi: 'Tên phải từ 2 ký tự',         en: 'Name must be at least 2 characters' },
'register.err_email':       { vi: 'Email không được rỗng',        en: 'Email is required' },
'register.err_pw_short':    { vi: 'Mật khẩu phải ít nhất 8 ký tự', en: 'Password must be at least 8 characters' },
'register.err_pw_upper':    { vi: 'Phải có ít nhất 1 chữ hoa',   en: 'Must contain at least 1 uppercase letter' },
'register.err_pw_match':    { vi: 'Mật khẩu xác nhận không khớp', en: 'Passwords do not match' },
'register.pw_strength.weak':   { vi: 'Yếu',      en: 'Weak' },
'register.pw_strength.fair':   { vi: 'Trung bình',en: 'Fair' },
'register.pw_strength.good':   { vi: 'Khá',       en: 'Good' },
'register.pw_strength.strong': { vi: 'Mạnh',      en: 'Strong' },
'register.pw_strength_lbl': { vi: 'Mật khẩu:',   en: 'Password:' },

// ── Login Page ────────────────────────────────────────────────────────────
'login.tagline':            { vi: 'Chào mừng trở lại Qtemplate 👋', en: 'Welcome back to Qtemplate 👋' },
'login.pw_label':           { vi: 'Mật khẩu',                    en: 'Password' },
'login.forgot_pw':          { vi: 'Quên mật khẩu?',              en: 'Forgot password?' },
'login.logging_in':         { vi: 'Đang đăng nhập...',           en: 'Signing in...' },
'login.or':                 { vi: 'hoặc',                        en: 'or' },
'login.no_account':         { vi: 'Chưa có tài khoản?',          en: "Don't have an account?" },
'login.register_free':      { vi: 'Đăng ký miễn phí ✨',         en: 'Register free ✨' },
'login.terms':              { vi: 'Bằng cách đăng nhập, bạn đồng ý với', en: 'By signing in, you agree to our' },
'login.terms_link':         { vi: 'Điều khoản dịch vụ',          en: 'Terms of Service' },
'login.resend_ok':          { vi: 'Email đã được gửi!',          en: 'Email sent!' },

// ── Auth Pages (Forgot/Reset/Verify) ──────────────────────────────────────
'auth.back_to_login':       { vi: 'Quay lại đăng nhập',          en: 'Back to login' },
'auth.forgot_title':        { vi: 'Quên mật khẩu?',              en: 'Forgot password?' },
'auth.forgot_subtitle':     { vi: 'Nhập email để nhận link đặt lại mật khẩu', en: 'Enter your email to receive a reset link' },
'auth.sending':             { vi: 'Đang gửi...',                  en: 'Sending...' },
'auth.send_reset_btn':      { vi: 'Gửi email đặt lại',           en: 'Send reset email' },
'auth.remember_pw':         { vi: 'Nhớ mật khẩu rồi?',          en: 'Remember your password?' },
'auth.reset_title':         { vi: 'Đặt lại mật khẩu',           en: 'Reset password' },
'auth.reset_subtitle':      { vi: 'Tạo mật khẩu mới cho tài khoản của bạn', en: 'Create a new password for your account' },
'auth.invalid_token':       { vi: 'Token không hợp lệ. Vui lòng yêu cầu lại.', en: 'Invalid token. Please request again.' },
'auth.new_pw_label':        { vi: 'Mật khẩu mới',                en: 'New password' },
'auth.confirm_pw_label':    { vi: 'Xác nhận mật khẩu',           en: 'Confirm password' },
'auth.confirm_pw_ph':       { vi: 'Nhập lại mật khẩu',           en: 'Re-enter password' },
'auth.resetting':           { vi: 'Đang đặt lại...',             en: 'Resetting...' },
'auth.reset_btn':           { vi: 'Đặt lại mật khẩu',           en: 'Reset password' },
'auth.pw_no_match':         { vi: 'Mật khẩu xác nhận không khớp', en: 'Passwords do not match' },
'auth.verifying':           { vi: 'Đang xác minh email...',      en: 'Verifying email...' },
'auth.verify_ok_title':     { vi: 'Xác minh thành công!',        en: 'Verified!' },
'auth.verify_ok_btn':       { vi: 'Đăng nhập ngay →',            en: 'Sign in now →' },
'auth.verify_fail_title':   { vi: 'Xác minh thất bại',           en: 'Verification failed' },
'auth.verify_fail_btn':     { vi: '← Về trang đăng nhập',        en: '← Back to login' },
'auth.token_invalid':       { vi: 'Token không hợp lệ',          en: 'Invalid token' },

// ── Profile Page ──────────────────────────────────────────────────────────
'profile.subtitle':         { vi: 'Quản lý thông tin cá nhân',   en: 'Manage your personal info' },
'profile.avatar_lbl':       { vi: 'Ảnh đại diện',                en: 'Avatar' },
'profile.change_avatar':    { vi: '📷 Đổi ảnh',                  en: '📷 Change photo' },
'profile.avatar_hint':      { vi: 'JPG, PNG, WebP · tối đa 2MB', en: 'JPG, PNG, WebP · max 2MB' },
'profile.personal_info':    { vi: 'Thông tin cá nhân',           en: 'Personal info' },
'profile.fullname_lbl':     { vi: 'Họ và tên',                   en: 'Full name' },
'profile.name_ph':          { vi: 'Nguyễn Văn A',                en: 'John Doe' },
'profile.email_fixed':      { vi: '🔒 Cố định',                  en: '🔒 Fixed' },
'profile.email_note':       { vi: 'Email không thể thay đổi',    en: 'Email cannot be changed' },
'profile.phone_lbl':        { vi: 'Số điện thoại',               en: 'Phone number' },
'profile.role_lbl':         { vi: 'Vai trò',                     en: 'Role' },
'profile.verified':         { vi: '✓ Đã xác minh',               en: '✓ Verified' },
'profile.not_verified':     { vi: '⚠ Chưa xác minh',            en: '⚠ Not verified' },
'profile.email_status':     { vi: 'Xác minh email',              en: 'Email verification' },
'profile.last_login':       { vi: 'Đăng nhập cuối',              en: 'Last login' },
'profile.created_at':       { vi: 'Ngày tạo',                    en: 'Created at' },
'profile.saving':           { vi: 'Đang lưu...',                 en: 'Saving...' },
'profile.save_btn':         { vi: '💾 Lưu thay đổi',             en: '💾 Save changes' },
'profile.size_warning':     { vi: 'File ảnh không được vượt quá 2MB', en: 'Image file must not exceed 2MB' },
'profile.load_err':         { vi: 'Không thể tải hồ sơ',         en: 'Failed to load profile' },
'profile.update_ok':        { vi: 'Cập nhật hồ sơ thành công!', en: 'Profile updated successfully!' },
'profile.update_err':       { vi: 'Cập nhật thất bại',           en: 'Update failed' },
'profile.avatar_ok':        { vi: 'Cập nhật avatar thành công!', en: 'Avatar updated successfully!' },
'profile.avatar_err':       { vi: 'Upload thất bại',             en: 'Upload failed' },

// ── Security Page ─────────────────────────────────────────────────────────
'security.subtitle':        { vi: 'Quản lý mật khẩu và bảo mật tài khoản', en: 'Manage your password and account security' },
'security.section_title':   { vi: 'Đổi mật khẩu',               en: 'Change password' },
'security.current_ph':      { vi: '••••••••',                    en: '••••••••' },
'security.new_ph':          { vi: 'NewPass@456',                 en: 'NewPass@456' },
'security.confirm_ph':      { vi: 'Nhập lại mật khẩu mới',      en: 'Re-enter new password' },
'security.changing':        { vi: 'Đang đổi...',                 en: 'Changing...' },
'security.change_btn':      { vi: '🔑 Đổi mật khẩu',            en: '🔑 Change password' },
'security.danger_zone':     { vi: 'Vùng nguy hiểm',              en: 'Danger zone' },
'security.delete_desc':     { vi: 'Xóa tài khoản sẽ vô hiệu hóa tài khoản của bạn. Hành động này không thể hoàn tác.', en: 'Deleting your account will deactivate it. This action cannot be undone.' },
'security.delete_btn':      { vi: '🗑️ Xóa tài khoản',           en: '🗑️ Delete account' },
'security.delete_modal_title': { vi: 'Xác nhận xóa tài khoản',  en: 'Confirm account deletion' },
'security.delete_warning':  { vi: 'Bạn sắp xóa tài khoản. Tất cả dữ liệu sẽ bị vô hiệu hóa và không thể phục hồi.', en: 'You are about to delete your account. All data will be deactivated and cannot be recovered.' },
'security.enter_pw_confirm':{ vi: 'Nhập mật khẩu để xác nhận',  en: 'Enter password to confirm' },
'security.deleting':        { vi: 'Đang xử lý...',               en: 'Processing...' },
'security.confirm_delete_btn': { vi: '🗑️ Xác nhận xóa',         en: '🗑️ Confirm delete' },
'security.pw_no_match':     { vi: 'Mật khẩu xác nhận không khớp', en: 'Passwords do not match' },
'security.change_ok':       { vi: 'Đổi mật khẩu thành công! Đang đăng xuất...', en: 'Password changed! Signing out...' },
'security.change_err':      { vi: 'Đổi mật khẩu thất bại',      en: 'Failed to change password' },
'security.delete_err':      { vi: 'Xóa tài khoản thất bại',     en: 'Failed to delete account' },

// ── Purchases Page ────────────────────────────────────────────────────────
'purchase.total':           { vi: 'Tổng',                        en: 'Total' },
'purchase.orders':          { vi: 'đơn hàng',                   en: 'orders' },
'purchase.no_status':       { vi: 'Không có đơn với trạng thái này.', en: 'No orders with this status.' },
'purchase.subtotal':        { vi: 'Tạm tính',                    en: 'Subtotal' },
'purchase.view_detail':     { vi: 'Chi tiết →',                  en: 'Details →' },
'purchase.total_label':     { vi: 'Tổng cộng',                   en: 'Total' },
'purchase.load_err':        { vi: 'Không thể tải đơn hàng',      en: 'Failed to load orders' },

// ── Order Detail Page ─────────────────────────────────────────────────────
'order.back':               { vi: 'Lịch sử mua hàng',           en: 'Purchase history' },
'order.items_title':        { vi: 'Sản phẩm',                   en: 'Items' },
'order.download_btn':       { vi: '⬇️ Tải',                     en: '⬇️ Download' },
'order.summary':            { vi: 'Tóm tắt đơn hàng',           en: 'Order summary' },
'order.subtotal':           { vi: 'Tạm tính',                    en: 'Subtotal' },
'order.discount':           { vi: 'Giảm giá',                   en: 'Discount' },
'order.total':              { vi: 'Tổng cộng',                   en: 'Total' },
'order.payment_info':       { vi: 'Thông tin thanh toán',        en: 'Payment info' },
'order.bank':               { vi: 'Ngân hàng',                  en: 'Bank' },
'order.transfer_content':   { vi: 'Nội dung CK',                en: 'Transfer content' },
'order.payment_amount':     { vi: 'Số tiền CK',                 en: 'Payment amount' },
'order.paid_at':            { vi: 'Thời gian TT',               en: 'Paid at' },
'order.sepay_code':         { vi: 'Mã Sepay',                   en: 'Sepay code' },
'order.fail_reason':        { vi: 'Lý do lỗi',                  en: 'Failure reason' },
'order.cancel_reason':      { vi: 'Lý do hủy',                  en: 'Cancel reason' },
'order.note':               { vi: 'Ghi chú',                    en: 'Note' },
'order.pay_btn':            { vi: '💳 Thanh toán ngay',          en: '💳 Pay now' },
'order.pay_creating':       { vi: 'Đang tạo...',                en: 'Creating...' },
'order.cancel_btn':         { vi: 'Hủy đơn',                    en: 'Cancel order' },
'order.load_err':           { vi: 'Không thể tải đơn hàng',     en: 'Failed to load order' },
'order.pay_err':            { vi: 'Tạo thanh toán thất bại',    en: 'Failed to create payment' },
'order.pay_ok':             { vi: 'Thanh toán thành công!',     en: 'Payment successful!' },
'order.cancel_ok':          { vi: 'Đã hủy đơn hàng',           en: 'Order cancelled' },
'order.cancel_err':         { vi: 'Hủy đơn thất bại',          en: 'Failed to cancel order' },

// ── Downloads Page ────────────────────────────────────────────────────────
'dl.history_title':         { vi: 'Lịch sử Download',            en: 'Download History' },
'dl.total':                 { vi: 'Tổng',                        en: 'Total' },
'dl.total_suffix':          { vi: 'template đã tải',             en: 'templates downloaded' },
'dl.col_count':             { vi: 'Số lần',                      en: 'Count' },
'dl.col_last':              { vi: 'Lần cuối tải',                en: 'Last download' },
'dl.col_action':            { vi: 'Thao tác',                    en: 'Action' },
'dl.view_btn':              { vi: '🗂️ Xem',                      en: '🗂️ View' },
'dl.empty_desc':            { vi: 'Tải template để xem lịch sử tại đây', en: 'Download templates to see history here' },

// ── Wishlist Page ─────────────────────────────────────────────────────────
'wish.list_title':          { vi: 'Danh sách yêu thích',         en: 'Wishlist' },
'wish.total':               { vi: 'template đã lưu',             en: 'templates saved' },
'wish.view_detail':         { vi: 'Xem chi tiết →',              en: 'View detail →' },
'wish.explore_btn':         { vi: 'Khám phá templates ngay →',   en: 'Explore templates →' },
'wish.remove_btn':          { vi: '🗑 Xóa',                      en: '🗑 Remove' },

// ── Templates Page ────────────────────────────────────────────────────────
'tpl.explore_title':        { vi: 'Khám phá',                    en: 'Explore' },
'tpl.explore_subtitle':     { vi: 'template chất lượng cao',     en: 'high-quality templates' },
'tpl.search_ph':            { vi: 'Tìm kiếm template...',        en: 'Search templates...' },
'tpl.all_categories':       { vi: 'Tất cả danh mục',             en: 'All categories' },
'tpl.all_prices':           { vi: '💰 Tất cả',                   en: '💰 All' },
'tpl.free_filter':          { vi: '🆓 Miễn phí',                 en: '🆓 Free' },
'tpl.paid_filter':          { vi: '💳 Trả phí',                  en: '💳 Paid' },
'tpl.all_tag':              { vi: 'Tất cả',                      en: 'All' },
'tpl.not_found':            { vi: 'Không tìm thấy template',     en: 'No templates found' },
'tpl.change_filter':        { vi: 'Thử thay đổi bộ lọc để xem thêm kết quả', en: 'Try changing filters to see more results' },
'tpl.wish_add_ok':          { vi: 'Đã thêm vào yêu thích',       en: 'Added to wishlist' },
'tpl.wish_remove_ok':       { vi: 'Đã xóa khỏi yêu thích',      en: 'Removed from wishlist' },
'tpl.load_err':             { vi: 'Không thể tải templates',     en: 'Failed to load templates' },
'tpl.free_label':           { vi: 'Miễn phí',                   en: 'Free' },
'tpl.advanced_filter':      { vi: 'Bộ lọc nâng cao',            en: 'Advanced filters' },
'tpl.clear_filters':        { vi: 'Xóa bộ lọc',                 en: 'Clear filters' },
'tpl.filter_active':        { vi: 'Đang lọc',                   en: 'Active filters' },
'tpl.techstack_ph':         { vi: 'TechStack (React, Vue...)',  en: 'TechStack (React, Vue...)' },
'tpl.min_price_ph':         { vi: 'Giá tối thiểu',              en: 'Min price' },
'tpl.max_price_ph':         { vi: 'Giá tối đa',                 en: 'Max price' },
'tpl.featured_label':       { vi: 'Nổi bật',                    en: 'Featured' },
'tpl.new_label':            { vi: 'Mới',                        en: 'New' },

// ── Sale Page ─────────────────────────────────────────────────────────────
'sale.nav_label':     { vi: 'Săn Sale',                                    en: 'Flash Sale' },
'sale.badge':         { vi: 'Flash Sale',                                  en: 'Flash Sale' },
'sale.title':         { vi: '🔥 Săn Sale',                                en: '🔥 Flash Sale' },
'sale.subtitle':      { vi: 'Đang có',                                     en: 'Currently' },
'sale.count_suffix':  { vi: 'template đang giảm giá',                     en: 'templates on sale' },
'sale.search_ph':     { vi: 'Tìm template đang sale...',                  en: 'Search sale templates...' },
'sale.load_err':      { vi: 'Không thể tải danh sách sale',               en: 'Failed to load sale templates' },
'sale.empty_title':   { vi: 'Chưa có template nào đang sale',             en: 'No templates on sale right now' },
'sale.empty_desc':    { vi: 'Admin chưa thiết lập sale. Quay lại sau!',   en: 'No sales set up yet. Check back later!' },
'sale.explore_btn':   { vi: 'Khám phá tất cả templates',                  en: 'Explore all templates' },
'sale.open_ended':    { vi: 'Không giới hạn',                              en: 'No expiry' },
'sale.expired':       { vi: 'Hết hạn',                                     en: 'Expired' },
'sale.time_left':     { vi: 'Thời gian còn lại',                           en: 'Time left' },
'sale.ending_soon':   { vi: 'Sắp kết thúc!',                               en: 'Ending soon!' },
'sale.on_sale':       { vi: 'Đang sale',                                   en: 'On sale' },
'sale.save':          { vi: 'Tiết kiệm',                                   en: 'Save' },
'sale.discount':      { vi: 'Giảm',                                        en: 'OFF' },
'sale.stat_products': { vi: 'sản phẩm',                                   en: 'products' },
'sale.stat_save_to':  { vi: 'Tiết kiệm tới',                              en: 'Save up to' },
'sale.unit_day':      { vi: 'ngày',                                        en: 'd' },
'sale.unit_hour':     { vi: 'giờ',                                         en: 'h' },
'sale.unit_min':      { vi: 'phút',                                        en: 'm' },
'sale.unit_sec':      { vi: 'giây',                                        en: 's' },

// ── Landing Page ────────────────────────────────────────────────────────────
'land.hero_badge':         { vi: 'Template Marketplace #1 Việt Nam',   en: 'Premium Template Marketplace' },
'land.hero_title_1':       { vi: 'Xây dựng website',                   en: 'Build stunning' },
'land.hero_title_2':       { vi: 'chuyên nghiệp',                      en: 'websites' },
'land.hero_title_3':       { vi: 'nhanh hơn bao giờ hết',              en: 'faster than ever' },
'land.hero_desc':          { vi: 'Hàng trăm template chất lượng cao, thiết kế đẹp, code sạch. Tải về và dùng ngay.',
                             en: 'Hundreds of premium templates, stunning design, clean code. Download and use immediately.' },
'land.search_ph':          { vi: 'Tìm template theo tên, công nghệ...', en: 'Search by name, tech stack...' },
'land.search_btn':         { vi: 'Tìm kiếm',                           en: 'Search' },
'land.cta_browse':         { vi: 'Khám phá ngay',                      en: 'Browse Templates' },
'land.cta_signup':         { vi: 'Đăng ký miễn phí',                   en: 'Sign up free' },

'land.stat_templates':     { vi: 'Templates',                           en: 'Templates' },
'land.stat_users':         { vi: 'Người dùng',                         en: 'Users' },
'land.stat_categories':    { vi: 'Danh mục',                           en: 'Categories' },
'land.stat_rating':        { vi: 'Đánh giá TB',                        en: 'Avg Rating' },

'land.banner_cta':         { vi: 'Xem ngay',                           en: 'View now' },

'land.cat_eyebrow':        { vi: 'Danh mục',                           en: 'Categories' },
'land.cat_title':          { vi: 'Tìm theo lĩnh vực',                 en: 'Browse by category' },
'land.see_all':            { vi: 'Xem tất cả',                         en: 'See all' },

'land.sale_ends':          { vi: 'Kết thúc sau',                       en: 'Ends in' },

'land.featured_eyebrow':   { vi: 'Nổi bật',                           en: 'Featured' },
'land.featured_title':     { vi: 'Templates được yêu thích nhất',      en: 'Most loved templates' },
'land.featured_subtitle':  { vi: 'Được chọn lọc kỹ càng, chất lượng đảm bảo', en: 'Handpicked, quality guaranteed' },

'land.new_eyebrow':        { vi: 'Mới nhất',                           en: 'New arrivals' },
'land.new_title':          { vi: 'Vừa ra mắt',                         en: 'Just launched' },
'land.new_subtitle':       { vi: 'Cập nhật thường xuyên, luôn có cái mới',   en: 'Updated regularly, always something new' },

'land.why_eyebrow':        { vi: 'Tại sao chọn Qtemplate',            en: 'Why Qtemplate' },
'land.why_title':          { vi: 'Mọi thứ bạn cần để ra mắt nhanh',  en: 'Everything you need to launch fast' },

'land.feat_ready_title':   { vi: 'Dùng ngay',                         en: 'Ready to use' },
'land.feat_ready_desc':    { vi: 'Tải về, cài đặt và chạy trong vài phút. Không cần setup phức tạp.',
                             en: 'Download, install and run in minutes. No complex setup needed.' },
'land.feat_design_title':  { vi: 'Thiết kế hiện đại',                 en: 'Modern design' },
'land.feat_design_desc':   { vi: 'Giao diện đẹp mắt, nhất quán, được thiết kế bởi designer chuyên nghiệp.',
                             en: 'Beautiful, consistent UI designed by professional designers.' },
'land.feat_code_title':    { vi: 'Code sạch',                          en: 'Clean code' },
'land.feat_code_desc':     { vi: 'Codebase rõ ràng, dễ customize, tuân thủ best practices.',
                             en: 'Clear codebase, easy to customize, following best practices.' },
'land.feat_resp_title':    { vi: 'Responsive 100%',                    en: 'Fully responsive' },
'land.feat_resp_desc':     { vi: 'Hiển thị hoàn hảo trên mọi thiết bị từ mobile đến desktop.',
                             en: 'Perfect display on all devices from mobile to desktop.' },
'land.feat_update_title':  { vi: 'Cập nhật liên tục',                 en: 'Regular updates' },
'land.feat_update_desc':   { vi: 'Tải về vĩnh viễn, nhận update miễn phí khi có phiên bản mới.',
                             en: 'Lifetime download, free updates when new versions release.' },
'land.feat_support_title': { vi: 'Hỗ trợ tận tâm',                   en: 'Dedicated support' },
'land.feat_support_desc':  { vi: 'Đội ngũ support sẵn sàng hỗ trợ khi bạn gặp vấn đề.',
                             en: 'Support team ready to help whenever you encounter issues.' },

'land.cta_eyebrow':        { vi: 'Bắt đầu ngay hôm nay',             en: 'Get started today' },
'land.cta_title':          { vi: 'Tìm template hoàn hảo cho dự án của bạn', en: 'Find the perfect template for your project' },
'land.cta_desc':           { vi: 'Hàng trăm lựa chọn chờ bạn khám phá. Miễn phí và trả phí.',
                             en: 'Hundreds of options waiting to be discovered. Free and premium.' },

// ── Template Detail Page ──────────────────────────────────────────────────
'tpl_detail.back':          { vi: 'Danh sách templates',         en: 'Templates list' },
'tpl_detail.description':   { vi: 'Mô tả',                      en: 'Description' },
'tpl_detail.tech_info':     { vi: 'Thông tin kỹ thuật',          en: 'Technical info' },
'tpl_detail.compatible':    { vi: 'Tương thích',                 en: 'Compatible with' },
'tpl_detail.format':        { vi: 'Định dạng',                   en: 'Format' },
'tpl_detail.version':       { vi: 'Phiên bản',                   en: 'Version' },
'tpl_detail.features':      { vi: 'Tính năng',                   en: 'Features' },
'tpl_detail.changelog':     { vi: 'Lịch sử thay đổi',           en: 'Changelog' },
'tpl_detail.reviews':       { vi: 'Đánh giá',                   en: 'Reviews' },
'tpl_detail.write_review':  { vi: '+ Viết đánh giá',            en: '+ Write review' },
'tpl_detail.no_reviews':    { vi: 'Chưa có đánh giá nào',       en: 'No reviews yet' },
'tpl_detail.admin_reply':   { vi: 'Phản hồi từ Admin',          en: 'Admin reply' },
'tpl_detail.sold':          { vi: 'Đã bán',                     en: 'Sold' },
'tpl_detail.views':         { vi: 'Lượt xem',                   en: 'Views' },
'tpl_detail.free':          { vi: 'Miễn phí',                   en: 'Free' },
'tpl_detail.coupon_title':  { vi: '🎟️ Nhập mã giảm giá / affiliate', en: '🎟️ Enter coupon / affiliate code' },
'tpl_detail.coupon_lbl':    { vi: 'Mã giảm giá',                en: 'Coupon code' },
'tpl_detail.check_btn':     { vi: 'Kiểm tra',                   en: 'Check' },
'tpl_detail.aff_lbl':       { vi: 'Mã affiliate',               en: 'Affiliate code' },
'tpl_detail.aff_auto':      { vi: '✓ tự động từ link',           en: '✓ auto from link' },
'tpl_detail.downloading':   { vi: 'Đang tải...',                en: 'Downloading...' },
'tpl_detail.download_btn':  { vi: '⬇️ Tải về ngay',             en: '⬇️ Download now' },
'tpl_detail.buy_loading':   { vi: 'Đang xử lý...',              en: 'Processing...' },
'tpl_detail.buy_btn':       { vi: '🛒 Mua ngay',                en: '🛒 Buy now' },
'tpl_detail.wishlisted':    { vi: '❤️ Đã thêm yêu thích',      en: '❤️ Wishlisted' },
'tpl_detail.add_wish':      { vi: '🤍 Thêm yêu thích',          en: '🤍 Add to wishlist' },
'tpl_detail.live_demo':     { vi: '🔗 Xem live demo',           en: '🔗 View live demo' },
'tpl_detail.preview':       { vi: '👁️ Xem preview',             en: '👁️ Preview' },
'tpl_detail.purchased':     { vi: 'Bạn đã mua template này',    en: 'You have purchased this template' },
'tpl_detail.review_title':  { vi: 'Viết đánh giá',              en: 'Write a review' },
'tpl_detail.review_star':   { vi: 'Đánh giá sao',               en: 'Star rating' },
'tpl_detail.review_title_lbl': { vi: 'Tiêu đề',                en: 'Title' },
'tpl_detail.review_title_ph': { vi: 'Template rất tốt!',        en: 'Great template!' },
'tpl_detail.review_comment':{ vi: 'Nhận xét',                   en: 'Comment' },
'tpl_detail.review_ph':     { vi: 'Chia sẻ trải nghiệm của bạn...', en: 'Share your experience...' },
'tpl_detail.review_submit': { vi: 'Gửi đánh giá',               en: 'Submit review' },
'tpl_detail.review_sending':{ vi: 'Đang gửi...',                en: 'Sending...' },
'tpl_detail.sale_end':      { vi: '⏰ Hết hạn',                 en: '⏰ Sale ends' },
'tpl_detail.gallery_hint':  { vi: '↔ kéo để chuyển · click để phóng to', en: '↔ drag to switch · click to zoom' },
'tpl_detail.wish_add_ok':   { vi: 'Đã thêm vào yêu thích',      en: 'Added to wishlist' },
'tpl_detail.wish_remove_ok':{ vi: 'Đã xóa khỏi yêu thích',      en: 'Removed from wishlist' },
'tpl_detail.load_err':      { vi: 'Không thể tải template',      en: 'Failed to load template' },
'tpl_detail.dl_ok':         { vi: 'Tải xuống thành công!',       en: 'Download successful!' },
'tpl_detail.dl_err':        { vi: 'Tải xuống thất bại',         en: 'Download failed' },
'tpl_detail.order_err':     { vi: 'Không thể tạo đơn hàng',     en: 'Failed to create order' },
'tpl_detail.review_ok':     { vi: 'Gửi đánh giá thành công!',   en: 'Review submitted!' },
'tpl_detail.review_err':    { vi: 'Gửi đánh giá thất bại',      en: 'Failed to submit review' },
'tpl_detail.coupon_valid':  { vi: '✓ Hợp lệ — giảm',            en: '✓ Valid — discount' },
'tpl_detail.coupon_invalid':{ vi: '✗',                           en: '✗' },

// ── Reviews Page ──────────────────────────────────────────────────────────
'reviews.title':            { vi: 'Đánh giá của tôi',            en: 'My Reviews' },
'reviews.count':            { vi: 'đánh giá',                   en: 'reviews' },
'reviews.status_pending':   { vi: '⏳ Chờ duyệt',               en: '⏳ Pending' },
'reviews.status_approved':  { vi: '✓ Đã duyệt',                 en: '✓ Approved' },
'reviews.status_rejected':  { vi: '✗ Từ chối',                  en: '✗ Rejected' },
'reviews.show':             { vi: 'Hiển thị',                   en: 'Show' },
'reviews.admin_reply':      { vi: 'Phản hồi từ Admin',          en: 'Admin reply' },
'reviews.view_tpl':         { vi: '🗂️ Xem template',             en: '🗂️ View template' },
'reviews.edit_btn':         { vi: '✏️ Sửa',                     en: '✏️ Edit' },
'reviews.delete_btn':       { vi: '🗑 Xóa',                     en: '🗑 Delete' },
'reviews.empty_desc':       { vi: 'Mua và sử dụng template để viết đánh giá', en: 'Purchase and use templates to write reviews' },
'reviews.confirm_delete':   { vi: 'Bạn có chắc muốn xóa review này?', en: 'Are you sure you want to delete this review?' },
'reviews.delete_ok':        { vi: 'Đã xóa đánh giá',            en: 'Review deleted' },
'reviews.delete_err':       { vi: 'Xóa thất bại',               en: 'Delete failed' },
'reviews.update_ok':        { vi: 'Cập nhật đánh giá thành công!', en: 'Review updated successfully!' },
'reviews.load_err':         { vi: 'Không thể tải đánh giá',     en: 'Failed to load reviews' },

// ── Tickets Page ──────────────────────────────────────────────────────────
'ticket.list_title':        { vi: 'Tickets hỗ trợ',             en: 'Support tickets' },
'ticket.new_btn':           { vi: '+ Tạo ticket',               en: '+ New ticket' },
'ticket.empty_desc':        { vi: 'Tạo ticket khi cần hỗ trợ từ đội ngũ chúng tôi', en: 'Create a ticket when you need support from our team' },
'ticket.col_status':        { vi: 'Trạng thái',                 en: 'Status' },
'ticket.col_created':       { vi: 'Ngày tạo',                   en: 'Created' },
'ticket.create_ok':         { vi: 'Tạo ticket thành công!',     en: 'Ticket created!' },
'ticket.load_err':          { vi: 'Không thể tải tickets',      en: 'Failed to load tickets' },
'ticket.back':              { vi: 'Danh sách tickets',           en: 'Tickets list' },
'ticket.attach':            { vi: '📎 Xem file đính kèm',       en: '📎 View attachment' },
'ticket.reply_title':       { vi: 'Gửi phản hồi',               en: 'Send reply' },
'ticket.reply_ph':          { vi: 'Nhập nội dung phản hồi...',  en: 'Enter your reply...' },
'ticket.attach_ph':         { vi: '🔗 URL file đính kèm (tùy chọn)', en: '🔗 Attachment URL (optional)' },
'ticket.reply_sending':     { vi: 'Đang gửi...',                en: 'Sending...' },
'ticket.reply_btn':         { vi: '📨 Gửi phản hồi',            en: '📨 Send reply' },
'ticket.closed_msg':        { vi: 'Ticket này đã đóng. Bạn không thể gửi thêm phản hồi.', en: 'This ticket is closed. You cannot send more replies.' },
'ticket.reply_ok':          { vi: 'Gửi phản hồi thành công!',  en: 'Reply sent!' },
'ticket.reply_err':         { vi: 'Gửi thất bại',               en: 'Failed to send' },
'ticket.detail_load_err':   { vi: 'Không thể tải ticket',       en: 'Failed to load ticket' },
'ticket.col_priority':      { vi: 'Priority',                   en: 'Priority' },
'ticket.col_ticket':        { vi: 'Ticket',                     en: 'Ticket' },
'ticket.badge_support':     { vi: '🎫 Hỗ trợ',                  en: '🎫 Support' },
'ticket.count_suffix':      { vi: 'ticket',                     en: 'tickets' },

// ── Affiliate Page ────────────────────────────────────────────────────────
'aff.subtitle':             { vi: 'Chương trình Affiliate',      en: 'Affiliate Program' },
'aff.tagline':              { vi: 'Kiếm tiền cùng Qtemplate',   en: 'Earn with Qtemplate' },
'aff.desc':                 { vi: 'Nhận hoa hồng cho mỗi giao dịch thành công qua link của bạn.', en: 'Earn commission for every successful transaction via your link.' },
'aff.rate':                 { vi: '10% hoa hồng',               en: '10% commission' },
'aff.admin_review':         { vi: 'Sau khi đăng ký, admin sẽ duyệt và kích hoạt tài khoản của bạn.', en: 'After registering, admin will review and activate your account.' },
'aff.registering':          { vi: 'Đang đăng ký...',            en: 'Registering...' },
'aff.register_btn':         { vi: '🚀 Đăng ký ngay',            en: '🚀 Register now' },
'aff.pending_banner':       { vi: '⏳ Tài khoản affiliate đang chờ admin duyệt.', en: '⏳ Affiliate account is pending admin approval.' },
'aff.code_lbl':             { vi: 'Mã:',                        en: 'Code:' },
'aff.rate_lbl':             { vi: 'Hoa hồng:',                  en: 'Commission:' },
'aff.total_commission':     { vi: 'Tổng hoa hồng',              en: 'Total commission' },
'aff.pending_amount':       { vi: 'Đang chờ trả',               en: 'Pending payout' },
'aff.paid_amount':          { vi: 'Đã thanh toán',              en: 'Paid out' },
'aff.link_title':           { vi: 'Link affiliate của bạn',     en: 'Your affiliate link' },
'aff.copy_btn':             { vi: '📋 Sao chép',                en: '📋 Copy' },
'aff.copied_btn':           { vi: '✓ Đã sao chép',             en: '✓ Copied' },
'aff.link_desc':            { vi: 'Chia sẻ link này. Khi có giao dịch thành công, bạn nhận được', en: 'Share this link. On each successful transaction, you earn' },
'aff.link_desc2':           { vi: 'hoa hồng.',                  en: 'commission.' },
'aff.history_title':        { vi: 'Lịch sử hoa hồng',           en: 'Commission history' },
'aff.transactions':         { vi: 'giao dịch',                  en: 'transactions' },
'aff.no_transactions':      { vi: 'Chưa có giao dịch nào',      en: 'No transactions yet' },
'aff.no_tx_desc':           { vi: 'Chia sẻ link affiliate để bắt đầu kiếm hoa hồng', en: 'Share your affiliate link to start earning' },
'aff.col_order':            { vi: 'Đơn hàng',                   en: 'Order' },
'aff.col_value':            { vi: 'Giá trị',                    en: 'Value' },
'aff.col_commission':       { vi: 'Hoa hồng',                   en: 'Commission' },
'aff.col_status':           { vi: 'Trạng thái',                 en: 'Status' },
'aff.tx_paid':              { vi: 'Đã trả',                     en: 'Paid' },
'aff.tx_pending':           { vi: 'Chờ trả',                    en: 'Pending' },
'aff.register_ok':          { vi: 'Đăng ký thành công!',        en: 'Registration successful!' },
'aff.not_registered_err':   { vi: 'chưa đăng ký',               en: 'not registered' },
'aff.dashboard_title':      { vi: 'Affiliate Dashboard',         en: 'Affiliate Dashboard' },
'aff.code_detail':          { vi: 'Mã:',                         en: 'Code:' },
'aff.rate_detail':          { vi: 'Hoa hồng:',                   en: 'Commission:' },

// ── Coupons Page ──────────────────────────────────────────────────────────
'coupon.hero_title':        { vi: 'Mã Giảm Giá',                en: 'Coupons' },
'coupon.hero_desc':         { vi: 'Copy mã → dán vào ô coupon khi mua template', en: 'Copy code → paste in coupon field when purchasing' },
'coupon.active_count':      { vi: 'mã đang hoạt động',          en: 'active coupons' },
'coupon.total_count':       { vi: 'tổng',                       en: 'total' },
'coupon.filter_all':        { vi: 'Tất cả',                     en: 'All' },
'coupon.filter_percent':    { vi: '% Giảm',                     en: '% Off' },
'coupon.filter_fixed':      { vi: 'Cố định',                    en: 'Fixed' },
'coupon.empty_title':       { vi: 'Chưa có mã nào',             en: 'No coupons yet' },
'coupon.empty_desc':        { vi: 'Hãy quay lại sau nhé!',      en: 'Check back later!' },
'coupon.explore_btn':       { vi: 'Xem templates →',            en: 'View templates →' },
'coupon.type_percent':      { vi: '🏷️ Giảm theo %',            en: '🏷️ Percentage discount' },
'coupon.type_fixed':        { vi: '💵 Giảm cố định',            en: '💵 Fixed discount' },
'coupon.max_discount':      { vi: 'Tối đa',                     en: 'Max' },
'coupon.expired':           { vi: '⛔ Hết hạn',                 en: '⛔ Expired' },
'coupon.full':              { vi: '🚫 Hết lượt',                en: '🚫 Fully used' },
'coupon.expiring_soon':     { vi: '⏰ Sắp hết',                 en: '⏰ Expiring soon' },
'coupon.available':         { vi: '✅ Còn dùng',                en: '✅ Available' },
'coupon.min_order':         { vi: 'Đơn tối thiểu',              en: 'Min. order' },
'coupon.valid_from':        { vi: 'Từ',                         en: 'From' },
'coupon.expires':           { vi: 'Hết hạn',                   en: 'Expires' },
'coupon.used_count':        { vi: 'Đã dùng',                   en: 'Used' },
'coupon.remaining':         { vi: 'Còn',                       en: 'Remaining' },
'coupon.lượt':              { vi: 'lượt',                      en: 'uses' },
'coupon.fully_used':        { vi: 'Đã hết',                    en: 'All used' },
'coupon.copy_ok':           { vi: '🎉 Đã sao chép mã',         en: '🎉 Copied code' },
'coupon.use_now':           { vi: 'Dùng ngay',                  en: 'Use now' },

// ── Order Cancel Modal ────────────────────────────────────────────────────
'modal.cancel_title':       { vi: 'Hủy đơn hàng',               en: 'Cancel order' },
'modal.cancel_warning':     { vi: '⚠️ Sau khi hủy, đơn hàng không thể khôi phục.', en: '⚠️ Once cancelled, the order cannot be restored.' },
'modal.cancel_reason_ph':   { vi: 'Lý do hủy (không bắt buộc)...', en: 'Cancel reason (optional)...' },
'modal.cancelling':         { vi: 'Đang hủy...',                en: 'Cancelling...' },
'modal.confirm_cancel':     { vi: 'Xác nhận hủy',               en: 'Confirm cancel' },

// ── Create Ticket Modal ───────────────────────────────────────────────────
'modal.ticket_title':       { vi: 'Tạo ticket hỗ trợ',          en: 'Create support ticket' },
'modal.ticket_subtitle':    { vi: 'Đội ngũ sẽ phản hồi sớm nhất có thể', en: 'Our team will respond as soon as possible' },
'modal.ticket_subject_lbl': { vi: 'Tiêu đề',                    en: 'Subject' },
'modal.ticket_subject_ph':  { vi: 'Không tải được file template...', en: 'Unable to download template file...' },
'modal.ticket_tpl_lbl':     { vi: 'Template ID (tùy chọn)',     en: 'Template ID (optional)' },
'modal.ticket_tpl_ph':      { vi: 'UUID của template (nếu có)', en: 'Template UUID (if applicable)' },
'modal.ticket_desc_lbl':    { vi: 'Mô tả chi tiết',             en: 'Description' },
'modal.ticket_desc_ph':     { vi: 'Mô tả vấn đề bạn gặp phải...', en: 'Describe the issue you encountered...' },
'modal.ticket_submitting':  { vi: 'Đang gửi...',                en: 'Sending...' },
'modal.ticket_submit':      { vi: '📨 Tạo ticket',              en: '📨 Create ticket' },
'modal.ticket_create_err':  { vi: 'Tạo ticket thất bại',        en: 'Failed to create ticket' },

// ── Review Edit Modal ─────────────────────────────────────────────────────
'modal.review_title':       { vi: 'Sửa đánh giá',               en: 'Edit review' },
'modal.review_star_lbl':    { vi: 'Đánh giá sao',               en: 'Star rating' },
'modal.review_title_lbl':   { vi: 'Tiêu đề',                    en: 'Title' },
'modal.review_title_ph':    { vi: 'Tiêu đề đánh giá',           en: 'Review title' },
'modal.review_comment_lbl': { vi: 'Nhận xét',                   en: 'Comment' },
'modal.review_comment_ph':  { vi: 'Nhận xét của bạn...',        en: 'Your comment...' },
'modal.review_saving':      { vi: 'Đang lưu...',                en: 'Saving...' },
'modal.review_save_btn':    { vi: 'Lưu thay đổi',               en: 'Save changes' },
'modal.review_update_err':  { vi: 'Cập nhật thất bại',          en: 'Update failed' },

// ── Payment Modal ─────────────────────────────────────────────────────────
'modal.pay_title':          { vi: 'Thanh toán đơn hàng',        en: 'Order payment' },
'modal.pay_success_title':  { vi: 'Thanh toán thành công!',     en: 'Payment successful!' },
'modal.pay_success_desc':   { vi: 'Đơn hàng đã được xác nhận', en: 'Your order has been confirmed' },
'modal.pay_note':           { vi: 'Chuyển khoản đúng nội dung và số tiền để đơn được xác nhận tự động.', en: 'Transfer the exact amount and content for automatic confirmation.' },
'modal.pay_bank':           { vi: 'Ngân hàng',                  en: 'Bank' },
'modal.pay_account':        { vi: 'Số tài khoản',               en: 'Account number' },
'modal.pay_amount':         { vi: 'Số tiền',                    en: 'Amount' },
'modal.pay_content':        { vi: 'Nội dung CK',                en: 'Transfer content' },
'modal.pay_waiting':        { vi: 'Đang chờ xác nhận thanh toán...', en: 'Waiting for payment confirmation...' },

// ── App 404 ───────────────────────────────────────────────────────────────
'app.404_title':            { vi: '404 – Không tìm thấy',       en: '404 – Not found' },
'app.404_back':             { vi: '← Về trang chủ',             en: '← Back to home' },

// ── News / Bảng tin ───────────────────────────────────────────────────────
'news.page_eyebrow':        { vi: 'Bảng tin',                    en: 'News' },
'news.page_title':          { vi: 'Tin tức & Cập nhật',          en: 'News & Updates' },
'news.page_subtitle':       { vi: 'Bài viết, hướng dẫn và cập nhật mới nhất từ chúng tôi', en: 'Latest articles, guides and updates from us' },
'news.search_ph':           { vi: 'Tìm kiếm bài viết...',        en: 'Search articles...' },
'news.empty_title':         { vi: 'Không có bài viết nào',       en: 'No articles found' },
'news.clear_search':        { vi: 'Xoá tìm kiếm',                en: 'Clear search' },
'news.prev':                { vi: '← Trước',                      en: '← Prev' },
'news.next':                { vi: 'Sau →',                        en: 'Next →' },
'news.featured_badge':      { vi: '⭐ Nổi bật',                   en: '⭐ Featured' },
'news.read_time':           { vi: 'phút đọc',                    en: 'min read' },
'news.views':               { vi: 'lượt xem',                    en: 'views' },
'news.author_prefix':       { vi: '✍️',                           en: '✍️' },
'news.date_prefix':         { vi: '📅',                           en: '📅' },
'news.back':                { vi: '← Bảng tin',                  en: '← News' },
'news.not_found_title':     { vi: 'Bài viết không tồn tại',      en: 'Article not found' },
'news.not_found_desc':      { vi: 'Bài viết đã bị xóa hoặc chưa được công khai.', en: 'The article may have been deleted or is not yet published.' },
'news.back_to_list':        { vi: '← Quay lại Bảng tin',         en: '← Back to News' },
'news.other_articles':      { vi: '← Bài viết khác',             en: '← Other articles' },
'news.tags_label':          { vi: 'Tags:',                        en: 'Tags:' },
'land.news_eyebrow':        { vi: 'Bảng tin',                    en: 'News' },
'land.news_title':          { vi: 'Tin tức mới nhất',            en: 'Latest news' },
'land.news_subtitle':       { vi: 'Cập nhật, hướng dẫn và bài viết từ chúng tôi', en: 'Updates, guides and articles from us' },
'land.news_see_all':        { vi: 'Xem tất cả',                  en: 'See all' },


// ── community ─────────────────────────────────────────────────────────────
'community.sort_hot':           { vi: '🔥 Nổi bật',                        en: '🔥 Hot' },
'community.sort_new':           { vi: '🆕 Mới nhất',                       en: '🆕 New' },
'community.sort_top':           { vi: '⭐ Hàng đầu',                       en: '⭐ Top' },

'community.badge':              { vi: 'Cộng đồng',                         en: 'Community' },
'community.page_title':         { vi: 'Diễn đàn Cộng đồng',                en: 'Community Forum' },
'community.page_subtitle':      { vi: 'Chia sẻ, thảo luận và kết nối với cộng đồng Qtemplate', en: 'Share, discuss and connect with the Qtemplate community' },

'community.composer_ph':        { vi: 'Chia sẻ điều gì đó... (Ctrl+Enter để đăng)', en: 'Share something... (Ctrl+Enter to post)' },
'community.btn_post':           { vi: '🚀 Đăng',                           en: '🚀 Post' },
'community.btn_save':           { vi: '💾 Lưu',                            en: '💾 Save' },
'community.btn_cancel':         { vi: 'Huỷ',                               en: 'Cancel' },
'community.btn_image':          { vi: '🖼 Ảnh',                            en: '🖼 Image' },
'community.img_too_large':      { vi: 'Ảnh không được vượt quá 5MB',       en: 'Image must be under 5MB' },
'community.content_too_long':   { vi: 'Nội dung không được vượt quá 3000 ký tự', en: 'Content must be under 3000 characters' },

'community.guest_title':        { vi: 'Đăng nhập để tham gia cộng đồng',   en: 'Sign in to join the community' },
'community.btn_login':          { vi: '🔐 Đăng nhập',                      en: '🔐 Sign in' },
'community.btn_register':       { vi: '✨ Đăng ký',                        en: '✨ Register' },

'community.btn_reply':          { vi: 'Trả lời',                           en: 'Reply' },
'community.btn_reply_close':    { vi: '✕ Đóng',                           en: '✕ Close' },
'community.btn_edit':           { vi: 'Sửa',                               en: 'Edit' },
'community.btn_delete':         { vi: 'Xóa',                               en: 'Delete' },
'community.btn_send':           { vi: 'Gửi',                               en: 'Send' },
'community.reply_ph':           { vi: 'Trả lời',                           en: 'Reply to' },

'community.comment_count':      { vi: 'bình luận',                         en: 'comments' },
'community.comment_btn':        { vi: 'Bình luận',                         en: 'Comment' },
'community.comment_ph':         { vi: 'Viết bình luận...',                 en: 'Write a comment...' },
'community.comment_login':      { vi: 'Đăng nhập để bình luận',            en: 'Sign in to comment' },
'community.comment_empty':      { vi: 'Chưa có bình luận nào — hãy là người đầu tiên!', en: 'No comments yet — be the first!' },
'community.comment_loading':    { vi: 'Đang tải...',                       en: 'Loading...' },
'community.comment_show_more':  { vi: 'Xem thêm',                         en: 'Show' },
'community.comment_replies':    { vi: 'câu trả lời',                       en: 'more replies' },
'community.comment_collapse':   { vi: '↑ Thu gọn bình luận',               en: '↑ Collapse comments' },
'community.comment_more':       { vi: '↓ Xem thêm',                       en: '↓ Show more' },
'community.comment_more_suffix':{ vi: 'bình luận',                         en: 'comments' },

'community.post_edited':        { vi: '(đã chỉnh sửa)',                    en: '(edited)' },
'community.post_btn_edit':      { vi: '✏️ Sửa',                           en: '✏️ Edit' },
'community.post_btn_delete':    { vi: '🗑 Xóa',                           en: '🗑 Delete' },
'community.post_delete_confirm':{ vi: 'Xóa bài viết này? Hành động không thể hoàn tác.', en: 'Delete this post? This action cannot be undone.' },
'community.post_deleted_ok':    { vi: 'Đã xóa bài viết',                  en: 'Post deleted' },
'community.comment_delete_confirm': { vi: 'Xóa bình luận này?',           en: 'Delete this comment?' },
'community.post_updated_ok':    { vi: 'Đã cập nhật bài viết',             en: 'Post updated' },
'community.post_created_ok':    { vi: 'Đã đăng bài!',                     en: 'Posted!' },
'community.like_login_warn':    { vi: 'Vui lòng đăng nhập để thích bài viết', en: 'Please sign in to like posts' },

'community.feed_empty_title':   { vi: 'Chưa có bài viết nào',             en: 'No posts yet' },
'community.feed_empty_desc':    { vi: 'Hãy là người đầu tiên chia sẻ với cộng đồng!', en: 'Be the first to share with the community!' },
'community.feed_load_more':     { vi: 'Xem thêm bài viết',                en: 'Load more posts' },
'community.feed_loading':       { vi: '⏳ Đang tải...',                   en: '⏳ Loading...' },
'community.feed_end':           { vi: 'Đã xem hết',                       en: 'Youve seen it all —' },
'community.feed_end_suffix':    { vi: 'bài viết',                         en: 'posts' },
'community.feed_new_banner':    { vi: 'bài viết mới — Nhấn để tải',       en: 'new posts — Click to load' },

'community.time_just_now':      { vi: 'Vừa xong',                         en: 'Just now' },
'community.time_mins':          { vi: 'phút trước',                       en: 'm ago' },
'community.time_hours':         { vi: 'giờ trước',                        en: 'h ago' },
'community.time_days':          { vi: 'ngày trước',                       en: 'd ago' },

// ── common.back_home ──────────────────────────────────────────────────────
'common.back_home':         { vi: 'Về trang chủ',               en: 'Back to home' },

};

// ─── Provider ────────────────────────────────────────────────────────────────
export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    try { return localStorage.getItem('lang') || 'vi'; } catch { return 'vi'; }
  });

  const toggleLang = () => {
    const next = lang === 'vi' ? 'en' : 'vi';
    setLang(next);
    try { localStorage.setItem('lang', next); } catch {}
  };

  /** Dịch key, fallback về key nếu không tìm thấy */
  const t = (key) => TRANSLATIONS[key]?.[lang] ?? key;

  return (
    <LangContext.Provider value={{ lang, toggleLang, t, isVi: lang === 'vi' }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used within LangProvider');
  return ctx;
};